spring.application.name: gateway-service
jwt:
  secretKey: fghfnxcmh78$(94905%*(8qeh3&#9(123470)wehf^&*ui54y89^09pa&*(ixjhcgio)6&S%7q

server.port: 8080

eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:lb://USER-SERVICE}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: post-service
          uri: ${POST_SERVICE_URI:lb://POST-SERVICE}
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connection-service
          uri: ${CONNECTION_SERVICE_URI:lb://CONNECTION-SERVICE}
          predicates:
            - Path=/api/v1/connection/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: media-service
          uri: ${MEDIA_SERVICE_URI:lb://MEDIA-SERVICE}
          predicates:
              - Path=/api/v1/media/**
          filters:
              - StripPrefix=2
              - name: AuthenticationFilter
