spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

uploadcare:
  public-key: 239d3b717fab1e10d362
  secret-key: 1787b0f3b91800c7f49c